# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  paypal_client_id: AXBZ10pJw-EPoDLdPM2gWTWpZiE-XcnAfjliP3_VtVFVNPvWOdGQnsSPZQy9J-hc2t_bTbcwXFypQq_w
  paypal_client_sec: ECvrh0o6ADjbwOhsfhThjlkcPSpiC3XH_38jwjbFlBCVDUdG0I794_9znqSsrM-23cYa33dPgKxyOyah

test:
  paypal_client_id: AXBZ10pJw-EPoDLdPM2gWTWpZiE-XcnAfjliP3_VtVFVNPvWOdGQnsSPZQy9J-hc2t_bTbcwXFypQq_w
  paypal_client_sec: ECvrh0o6ADjbwOhsfhThjlkcPSpiC3XH_38jwjbFlBCVDUdG0I794_9znqSsrM-23cYa33dPgKxyOyah